repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: flake8
    -   id: trailing-whitespace
      #-   id: detect-aws-credentials
      #-   args: [allow-missing-credentials]
