repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
